# Generated by Django 5.2.8 on 2025-11-10 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.IntegerField(default=1)),
                ('started_at', models.FloatField(default=0.0)),
                ('finished_at', models.FloatField(default=0.0)),
                ('total_time_ms', models.FloatField(default=0.0)),
                ('features_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeystrokeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('key', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('t', models.FloatField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='collector.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='.tie5Roanl', max_length=32)),
                ('index', models.IntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.participant')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.session'),
        ),
    ]
